name: Docker Build and Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set image tag
        id: set_tag
        run: |
          echo "IMAGE_TAG=1.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag pacman-game:${{ env.IMAGE_TAG }}
        
      - name: Security Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: pacman-game:${{ env.IMAGE_TAG }}
          exit-code: '0'
          severity: 'CRITICAL'   
          
      - name: Push Docker image to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag pacman-game:${{ env.IMAGE_TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/pacman-game:${{ env.IMAGE_TAG }}
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pacman-game:${{ env.IMAGE_TAG }}
